kind: pipeline
type: docker
name: sealway-strava-build

platform:
  arch: amd64

steps:
- name: grafana-annotation-start
  image: fdeschenes/drone-grafana-annotation
  settings:
    api_key:
      from_secret: vault_grafana_api_key
    tags:
      - build
      - start
    text: Start build sealway-strava by Drone
    url:
      from_secret: grafana_url

- name: docker-build-go
  image: docker
  privileged: true
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker buildx create --name multy-build --use
  - docker buildx build -t sealway/strava --platform linux/amd64,linux/arm64 --push .
  environment:
    DOCKER_USERNAME:
      from_secret: vault_docker_username
    DOCKER_PASSWORD:
      from_secret: vault_docker_password
  volumes:
  - name: docker
    path: /run/docker.sock

- name: nomad-deploy-sealway
  image: pachman/drone-nomad
  settings:
    addr:
      from_secret: nomad_url
    vault_token:
      from_secret: vault_token_nomad
    template: ./strava.nomad

- name: discord-notification
  image: appleboy/drone-discord
  privileged: true
  settings:
    webhook_id: 
      from_secret: vault_discord_webhook_id
    webhook_token: 
      from_secret: vault_discord_webhook_token
    message: >
      {{#success build.status}}
        :white_check_mark: build `sealway-strava` {{build.number}} succeeded. Good job.
      :notepad_spiral: commit:
      ```{{commit.message}}```
      :ship: https://hub.docker.com/u/sealway
      {{else}}
         :sos: build `sealway-strava` {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    status:
    - success
    - failure

- name: grafana-annotation-finish
  image: fdeschenes/drone-grafana-annotation
  settings:
    api_key:
      from_secret: vault_grafana_api_key
    tags:
      - build
      - finish
    text: Finish build sealway-strava by Drone
    url:
      from_secret: grafana_url
  when:
    status:
    - success
    - failure

volumes:
- name: docker
  host:
    path: /run/docker.sock

trigger:
  branch:
  - main
  event:
  - push

# devops

---
kind: secret
name: nomad_url
get:
  path: devops/nomad
  name: url

---
kind: secret
name: grafana_url
get:
  path: devops/grafana
  name: url

---
kind: secret
name: vault_docker_password
get:
  path: devops/docker_hub/sealway
  name: token

---
kind: secret
name: vault_docker_username
get:
  path: devops/docker_hub/sealway
  name: username

---
kind: secret
name: vault_grafana_api_key
get:
  path: devops/grafana
  name: api_key

---
kind: secret
name: vault_discord_webhook_id
get:
  path: devops/discord/drone
  name: webhook_id

---
kind: secret
name: vault_discord_webhook_token
get:
  path: devops/discord/drone
  name: webhook_token

---
kind: secret
name: vault_token_nomad
get:
  path: devops/vault
  name: token_nomad