/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type SummarySegment struct {
	// The unique identifier of this segment
	ID int64 `bson:"id" json:"id,omitempty"`
	// The name of this segment
	Name         string `bson:"name" json:"name,omitempty"`
	ActivityType string `bson:"activity_type" json:"activity_type,omitempty"`
	// The segment's distance, in meters
	Distance float64 `bson:"distance" json:"distance,omitempty"`
	// The segment's average grade, in percents
	AverageGrade float64 `bson:"average_grade" json:"average_grade,omitempty"`
	// The segments's maximum grade, in percents
	MaximumGrade float64 `bson:"maximum_grade" json:"maximum_grade,omitempty"`
	// The segments's highest elevation, in meters
	ElevationHigh float64 `bson:"elevation_high" json:"elevation_high,omitempty"`
	// The segments's lowest elevation, in meters
	ElevationLow float64    `bson:"elevation_low" json:"elevation_low,omitempty"`
	StartLatlng  *[]float64 `bson:"start_latlng" json:"start_latlng,omitempty"`
	EndLatlng    *[]float64 `bson:"end_latlng" json:"end_latlng,omitempty"`
	// The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category.
	ClimbCategory int64 `bson:"climb_category" json:"climb_category,omitempty"`
	// The segments's city.
	City string `bson:"city" json:"city,omitempty"`
	// The segments's state or geographical region.
	State string `bson:"state" json:"state,omitempty"`
	// The segment's country.
	Country string `bson:"country" json:"country,omitempty"`
	// Whether this segment is private.
	Private             bool                    `bson:"private" json:"private,omitempty"`
	AthletePrEffort     *SummarySegmentEffort   `bson:"athlete_pr_effort" json:"athlete_pr_effort,omitempty"`
	AthleteSegmentStats *SummaryPrSegmentEffort `bson:"athlete_segment_stats" json:"athlete_segment_stats,omitempty"`
}
