// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DetailedActivity struct {
	ID          string  `json:"id"`
	Distance    float64 `json:"distance"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewAthleteToken struct {
	AthleteID int    `json:"athleteId"`
	Access    string `json:"access"`
	Refresh   string `json:"refresh"`
	Expired   string `json:"expired"`
}
