/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package strava

type StreamSet struct {
	Time           *TimeStream           `bson:"time" json:"time,omitempty"`
	Distance       *DistanceStream       `bson:"distance" json:"distance,omitempty"`
	Latlng         *LatLngStream         `bson:"latlng" json:"latlng,omitempty"`
	Altitude       *AltitudeStream       `bson:"altitude" json:"altitude,omitempty"`
	VelocitySmooth *SmoothVelocityStream `bson:"velocity_smooth" json:"velocity_smooth,omitempty"`
	Heartrate      *HeartrateStream      `bson:"heartrate" json:"heartrate,omitempty"`
	Cadence        *CadenceStream        `bson:"cadence" json:"cadence,omitempty"`
	Watts          *PowerStream          `bson:"watts" json:"watts,omitempty"`
	Temp           *TemperatureStream    `bson:"temp" json:"temp,omitempty"`
	Moving         *MovingStream         `bson:"moving" json:"moving,omitempty"`
	GradeSmooth    *SmoothGradeStream    `bson:"grade_smooth" json:"grade_smooth,omitempty"`
}
